apiVersion: apps/v1
kind: Deployment
metadata:
  name: spokn-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spokn-frontend
  template:
    metadata:
      labels:
        app: spokn-frontend
    spec:
      containers:
      - name: spokn-frontend
        image: 12809/spokn-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "http://spokn-backend-svc:4000"
---
apiVersion: v1
kind: Service
metadata:
  name: spokn-frontend-svc
spec:
  selector:
    app: spokn-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer